<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Add Product</title>
</head>
<body>
<form method="post" action="/products/add">
    <input name="name" type="text" placeholder="Enter name"/> <br><br>
    <input name="price" type="text" placeholder="Enter price"/> <br><br>
    <input type="submit" value="Add">
</form>
</body>
</html>